apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: staging-voting-app-postgresql
  annotations:
    snapshot.alpha.kubernetes.io/snapshot: voting-postgresql-snap
spec:
  accessModes:
     - ReadWriteOnce
  storageClassName: stork-snapshot-sc
  resources:
    requests:
      storage: 8Gi